
#ifndef BIGTON_ERROR_H
#define BIGTON_ERROR_H

typedef enum BigtonError {
    BIGTONE_NONE,

    BIGTONE_INT_DIVISION_BY_ZERO,
    BIGTONE_BY_PROGRAM,
    BIGTONE_TUPLE_INDEX_OOB,
    BIGTONE_INVALID_OBJECT_MEMBER,
    BIGTONE_ARRAY_INDEX_OOB,
    BIGTONE_OPERANDS_NOT_NUMBERS,
    BIGTONE_OPERAND_NOT_INTEGER,
    BIGTONE_OPERAND_NOT_TUPLE,
    BIGTONE_OPERAND_NOT_OBJECT,
    BIGTONE_OPERAND_NOT_ARRAY,
    BIGTONE_EXCEEDED_MAXIMUM_CALL_DEPTH,
    BIGTONE_TUPLE_TOO_BIG,
    BIGTONE_EXCEEDED_MEMORY_LIMIT,
    
    BIGTONE_INT_INCOMPLETE_PROGRAM,
    BIGTONE_INT_INVALID_CONST_STRING,
    BIGTONE_INT_STACK_EMPTY,
    BIGTONE_INT_STACK_IDX_OOB,
    BIGTONE_INT_SCOPE_STACK_EMPTY,
    BIGTONE_INT_GLOBAL_VAR_REF_INVALID,
    BIGTONE_INT_INSTR_COUNTER_OOB,
    BIGTONE_INT_LOCAL_IDX_OOB,
    BIGTONE_INT_SHAPE_PROP_IDX_OOB,
    BIGTONE_INT_SHAPE_ID_OOB,
    BIGTONE_INT_BUILTIN_FUN_REF_INVALID,
    BIGTONE_INT_FUN_REF_INVALID
} bigton_error_t;

#endif