
package schwalbe.ventura.client

import schwalbe.ventura.engine.Language
import schwalbe.ventura.engine.Localizations
import schwalbe.ventura.engine.Resource
import schwalbe.ventura.engine.loadLanguages
import kotlinx.serialization.Serializable

@Serializable
enum class GameLanguage(
    override val id: String, val nativeName: String, val englishName: String
) : Language<GameLanguage> {
    ENGLISH     ("en", "English",   "English"   ),
    GERMAN      ("de", "Deutsch",   "German"    ),
    BULGARIAN   ("bg", "Български", "Bulgarian" );
}

enum class LocalKeys {
    // Common Button Strings
    BUTTON_GO_BACK,
    BUTTON_DISCONNECT,

    // Loading Game Screen
    TITLE_LOADING,

    // Language Select Screen
    TITLE_SELECT_LANGUAGE,

    // Settings Screen
    TITLE_SETTINGS,
    SECTION_AUDIO_SETTINGS,
    DESCRIPTION_AUDIO_SETTINGS,
    SETTING_GENERAL_VOLUME,
    DESCRIPTION_GENERAL_VOLUME,
    SETTING_MUSIC_VOLUME,
    DESCRIPTION_MUSIC_VOLUME,
    SETTING_SFX_VOLUME,
    DESCRIPTION_SFX_VOLUME,
    SECTION_DISPLAY_SETTINGS,
    DESCRIPTION_DISPLAY_SETTINGS,
    SETTING_FULLSCREEN,
    DESCRIPTION_FULLSCREEN,
    SETTING_VSYNC,
    DESCRIPTION_VSYNC,
    SECTION_CODE_EDITING_SETTINGS,
    DESCRIPTION_CODE_EDITING_SETTINGS,
    SETTING_ADVANCED_EDITING,
    DESCRIPTION_ADVANCED_EDITING,
    SETTING_AUTO_RESTART,
    DESCRIPTION_AUTO_RESTART,

    // Advanced Editing Mode Dialog
    NAME_SIMPLE_EDITING_MODE,
    DESCRIPTION_SIMPLE_EDITING_MODE,
    NAME_ADVANCED_EDITING_MODE,
    DESCRIPTION_ADVANCED_EDITING_MODE,
    BUTTON_SELECT_MODE,

    // Server List Screen
    BUTTON_ADD_SERVER,
    TEXT_CLIENT_BUILD_VERSION,

    // Server Edit Screen
    TITLE_EDIT_SERVER,
    LABEL_SERVER_NAME,
    PLACEHOLDER_SERVER_NAME,
    LABEL_SERVER_ADDRESS,
    PLACEHOLDER_SERVER_ADDRESS,
    LABEL_SERVER_PORT,
    PLACEHOLDER_SERVER_PORT,
    BUTTON_SERVER_CONFIRM,
    BUTTON_SERVER_DISCARD,

    // Connecting To Server Screen
    TITLE_CONNECTING_TO_SERVER,
    BUTTON_CANCEL_CONNECTION,

    // Connection Failed Screen
    TITLE_CONNECTION_TO_SERVER_FAILED,

    // Login Screen
    TITLE_LOGIN,
    TITLE_SIGN_UP,
    LABEL_USERNAME,
    PLACEHOLDER_USERNAME,
    LABEL_PASSWORD,
    PLACEHOLDER_PASSWORD,
    LABEL_REPEAT_PASSWORD,
    PLACEHOLDER_REPEAT_PASSWORD,
    BUTTON_LOG_IN,
    BUTTON_SIGN_UP,

    // Inventory Screen
    TITLE_INVENTORY,
    PLACEHOLDER_INVENTORY_EMPTY,

    // Robot Editing Screen
    LABEL_ROBOT_STAT_HEALTH,
    LABEL_ROBOT_STAT_MEMORY,
    LABEL_ROBOT_STAT_PROCESSOR,
    BUTTON_ROBOT_START,
    BUTTON_ROBOT_STOP,
    TITLE_SELECT_SOURCE_FILE,
    TITLE_ROBOT_ATTACHMENTS,
    TITLE_ROBOT_CODE_FILES,
    BUTTON_ADD_CODE_FILE,
    BUTTON_EDIT_ROBOT_CODE_FILE,
    BUTTON_EDIT_ROBOT_CODE_FILE_SHORT,
    BUTTON_ENABLE_ADVANCED_EDITING,
    BUTTON_REPAIR_ROBOT,
    BUTTON_DESTROY_ROBOT,
    BUTTON_REMOVE_ITEM,
    BUTTON_CANCEL_EDIT,

    // Code Editing Screen
    BUTTON_CREATE_FILE,
    BUTTON_CREATE_FOLDER,
    BUTTON_RENAME_FILE,
    BUTTON_COPY_FILE,
    BUTTON_PASTE_FILES,
    BUTTON_DELETE_FILE,
    BUTTON_OPEN_IN_FILE_EXPLORER,
    TITLE_ENTER_FILE_NAME,
    BUTTON_CANCEL_FILE_ACTION,

    // Escape Menu Screen
    BUTTON_BACK_TO_GAME,
    BUTTON_LEAVE_INTERIOR,
    BUTTON_LOG_OUT,

    // Error Strings
    ERROR_INVALID_ACCOUNT_PARAMS,
    ERROR_INVALID_ACCOUNT_CREDS,
    ERROR_SESSION_CREATION_COOLDOWN,
    ERROR_INVALID_SESSION_CREDS,
    ERROR_ACCOUNT_ALREADY_ONLINE,
    ERROR_PASSWORDS_DONT_MATCH,
    ERROR_USERNAME_TOO_SHORT,
    ERROR_PASSWORD_TOO_SHORT,
    ERROR_SERVER_OUTDATED,
    ERROR_CLIENT_OUTDATED
}

val localized: Resource<Localizations<GameLanguage, LocalKeys>>
    = Localizations.loadLanguages("res/localizations", GameLanguage.ENGLISH)