/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class schwalbe_ventura_bigton_runtime_BigtonValue */

#ifndef _Included_schwalbe_ventura_bigton_runtime_BigtonValue
#define _Included_schwalbe_ventura_bigton_runtime_BigtonValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    createNull
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_createNull
  (JNIEnv *, jclass);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    createInt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_createInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    createFloat
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_createFloat
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    createString
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_createString
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    createTuple
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_createTuple
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    createArray
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_createArray
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_copy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    free
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_free
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getInt
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getFloat
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getFloat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getTupleLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getTupleLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getTupleMember
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getTupleMember
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    setTupleMember
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_setTupleMember
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    findObjectPropDyn
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_findObjectPropDyn
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    findObjectPropConst
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_findObjectPropConst
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getObjectSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getObjectSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getObjectMember
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getObjectMember
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    setObjectMember
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_setObjectMember
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getArrayLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getArrayLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    getArrayElement
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_getArrayElement
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonValue
 * Method:    setArrayElement
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonValue_setArrayElement
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
