/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class schwalbe_ventura_bigton_runtime_BigtonRuntime */

#ifndef _Included_schwalbe_ventura_bigton_runtime_BigtonRuntime
#define _Included_schwalbe_ventura_bigton_runtime_BigtonRuntime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    createSettings
 * Signature: (JJII)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_createSettings
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    freeSettings
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_freeSettings
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    create
 * Signature: (JLjava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_create
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    debugLoadedProgram
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_debugLoadedProgram
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getLogLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getLogLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getLogString
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getLogString
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    addLogLine
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_addLogLine
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getTraceLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getTraceLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getTrace
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getTrace
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getStackLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getStackLength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    pushStack
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_pushStack
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getStack
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getStack
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    popStack
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_popStack
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    hasError
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_hasError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getError
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getCurrentFile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getCurrentFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getCurrentLine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getCurrentLine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getUsedMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getUsedMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getAwaitingBuiltinFun
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getAwaitingBuiltinFun
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    getConstString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_getConstString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    startTick
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_startTick
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonRuntime
 * Method:    execBatch
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonRuntime_execBatch
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
