/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class schwalbe_ventura_bigton_runtime_BigtonTrace */

#ifndef _Included_schwalbe_ventura_bigton_runtime_BigtonTrace
#define _Included_schwalbe_ventura_bigton_runtime_BigtonTrace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonTrace
 * Method:    getName
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonTrace_getName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonTrace
 * Method:    getDeclFile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonTrace_getDeclFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonTrace
 * Method:    getDeclLine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonTrace_getDeclLine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonTrace
 * Method:    getFromFile
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonTrace_getFromFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonTrace
 * Method:    getFromLine
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonTrace_getFromLine
  (JNIEnv *, jclass, jlong);

/*
 * Class:     schwalbe_ventura_bigton_runtime_BigtonTrace
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_schwalbe_ventura_bigton_runtime_BigtonTrace_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
